# Generated by Django 5.0.1 on 2024-01-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("img_detect", "0003_rename_title_imgdetect_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="imgdetect",
            name="inference_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
