# Generated by Django 5.0.1 on 2024-01-14 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("img_detect", "0004_imgdetect_inference_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imgdetect",
            name="inference_label",
        ),
    ]
