# Generated by Django 5.0.1 on 2024-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("img_detect", "0005_remove_imgdetect_inference_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="imgdetect",
            name="inference_label",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
