# Generated by Django 5.0.1 on 2024-01-05 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="status",
            new_name="review",
        ),
    ]
