# Generated by Django 5.0.1 on 2024-01-05 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_status_product_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descrition",
            new_name="description",
        ),
    ]
